name: newsapp_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  google_fonts: ^5.1.0
  iconly: ^1.0.1
  fancy_shimmer_image: ^2.0.3
  shimmer: ^3.0.0
  card_swiper: ^2.0.4
  page_transition: ^2.0.9
  flutter_iconly: ^1.0.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_inappwebview: ^5.7.2+3
  webview_flutter: ^4.2.2
  share_plus: ^7.0.2
  url_launcher: ^6.1.12
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
